export const doctors = [
  {
    id: 1,
    name: "Dr. Priya Verma",
    image:
      "https://plus.unsplash.com/premium_photo-1658506671316-0b293df7c72b?fm=jpg&q=60&w=3000&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8ZG9jdG9yfGVufDB8fDB8fHww",
    specialization: "Radiologist, Urologist",
    appointmentDate: "2024-01-13",
    experience: "24 years",
    languages: ["Bengali", "Telugu", "Punjabi"],
    hospitals: ["Manipal Hospital", "Fortis Healthcare"],
  },
  {
    id: 2,
    name: "Dr. Amit Reddy",
    image:
      "https://media.istockphoto.com/id/177373093/photo/indian-male-doctor.jpg?s=612x612&w=0&k=20&c=5FkfKdCYERkAg65cQtdqeO_D0JMv6vrEdPw3mX1Lkfg=",
    specialization: "Gastroenterologist",
    appointmentDate: "2024-01-24",
    experience: "24 years",
    languages: ["Hindi", "English", "Punjabi"],
    hospitals: ["Medanta"],
  },
  {
    id: 3,
    name: "Dr. Amit Das",
    image:
      "https://img.freepik.com/free-photo/beautiful-young-female-doctor-looking-camera-office_1301-7807.jpg",
    specialization: "Psychiatrist, Rheumatologist",
    appointmentDate: "2024-05-26",
    experience: "16 years",
    languages: ["Marathi", "English", "Kannada"],
    hospitals: ["Max Healthcare"],
  },
  {
    id: 4,
    name: "Dr. Sunil Reddy",
    image:
      "https://png.pngtree.com/png-vector/20230928/ourmid/pngtree-young-afro-professional-doctor-png-image_10148632.png",
    specialization: "Pediatrician, Gynecologist",
    appointmentDate: "2024-04-15",
    experience: "23 years",
    languages: ["Bengali"],
    hospitals: ["Kokilaben Dhirubhai Ambani Hospital"],
  },
  {
    id: 5,
    name: "Dr. Ravi Das",
    image:
      "https://www.shutterstock.com/image-photo/profile-photo-attractive-family-doc-600nw-1724693776.jpg",
    specialization: "Gastroenterologist, Pediatrician",
    appointmentDate: "2024-09-08",
    experience: "23 years",
    languages: ["English"],
    hospitals: ["Fortis Healthcare"],
  },
  {
    id: 6,
    name: "Dr. Ravi Singh",
    image:
      "https://media.istockphoto.com/id/638647058/photo/we-offer-our-patients-premium-healthcare-here.jpg?s=612x612&w=0&k=20&c=pek5ehwgsZNPemeEh4bObQ1U5DRPEs0WHleosG-daa8=",
    specialization: "ENT Specialist, Cardiologist",
    appointmentDate: "2024-03-23",
    experience: "4 years",
    languages: ["English", "Hindi"],
    hospitals: ["Kokilaben Dhirubhai Ambani Hospital"],
  },
  {
    id: 7,
    name: "Dr. Priya Kumar",
    image:
      "https://t4.ftcdn.net/jpg/07/07/89/33/360_F_707893394_5DEhlBjWOmse1nyu0rC9T7ZRvsAFDkYC.jpg",
    specialization: "Allergist, Radiologist",
    appointmentDate: "2024-04-28",
    experience: "23 years",
    languages: ["Urdu"],
    hospitals: ["Kokilaben Dhirubhai Ambani Hospital"],
  },
  {
    id: 8,
    name: "Dr. Pooja Das",
    image:
      "https://cdn.pixabay.com/photo/2024/09/03/15/21/ai-generated-9019520_640.png",
    specialization: "Gastroenterologist, Gynecologist, Orthopedist",
    appointmentDate: "2024-10-23",
    experience: "23 years",
    languages: ["Marathi", "English", "Tamil", "Kannada"],
    hospitals: ["Manipal Hospital", "AIIMS"],
  },
  {
    id: 9,
    name: "Dr. Pooja Sharma",
    image:
      "https://static.vecteezy.com/system/resources/thumbnails/026/375/249/small/ai-generative-portrait-of-confident-male-doctor-in-white-coat-and-stethoscope-standing-with-arms-crossed-and-looking-at-camera-photo.jpg",
    specialization: "Allergist, Oncologist",
    appointmentDate: "2024-05-11",
    experience: "26 years",
    languages: ["Malayalam", "Telugu"],
    hospitals: ["Medanta"],
  },
  {
    id: 10,
    name: "Dr. Raj Gupta",
    image:
      "https://static.vecteezy.com/system/resources/thumbnails/028/287/555/small/an-indian-young-female-doctor-isolated-on-green-ai-generated-photo.jpg",
    specialization: "Radiologist",
    appointmentDate: "2024-01-26",
    experience: "1 years",
    languages: ["Hindi"],
    hospitals: ["Medanta"],
  },
  {
    id: 11,
    name: "Dr. Pooja Kumar",
    image:
      "https://png.pngtree.com/png-clipart/20230918/ourmid/pngtree-photo-men-doctor-physician-chest-smiling-png-image_10132895.png",
    specialization: "Thoracic Surgeon, Ophthalmologist, Gynecologist",
    appointmentDate: "2024-05-28",
    experience: "22 years",
    languages: ["Gujarati"],
    hospitals: ["Medanta", "BLK-Max Super Specialty Hospital"],
  },
  {
    id: 12,
    name: "Dr. Kavita Kumar",
    image:
      "https://media.istockphoto.com/id/1292015214/photo/portrait-female-doctor-stock-photo.jpg?s=612x612&w=0&k=20&c=nr4XaWnRPQnWqwhzahajZhskIDG1yK9DmIteV5gpUOI=",
    specialization: "Anesthesiologist",
    appointmentDate: "2024-05-27",
    experience: "2 years",
    languages: ["Tamil", "Bengali", "Marathi"],
    hospitals: ["Max Healthcare", "Medanta"],
  },
  {
    id: 13,
    name: "Dr. Ravi Singh",
    image: "",
    specialization: "Orthopedist, Gynecologist, Dermatologist",
    appointmentDate: "2024-11-24",
    experience: "10 years",
    languages: ["Kannada", "English", "Punjabi"],
    hospitals: ["Max Healthcare", "Kokilaben Dhirubhai Ambani Hospital"],
  },
  {
    id: 14,
    name: "Dr. Amit Kumar",
    image:
      "https://t3.ftcdn.net/jpg/02/25/70/72/360_F_225707294_V0jKFrHm1Bm5mLQjTAhKFplaWQIgdHby.jpg",
    specialization: "Pulmonologist, Plastic Surgeon, Gastroenterologist",
    appointmentDate: "2024-01-20",
    experience: "3 years",
    languages: ["English", "Marathi"],
    hospitals: ["Fortis Healthcare", "AIIMS"],
  },
  {
    id: 15,
    name: "Dr. Raj Singh",
    image:
      "https://media.istockphoto.com/id/179002723/photo/indian-doctors-or-medical-team.jpg?s=612x612&w=0&k=20&c=GDtzdcnIYFo4pWLcmX78elzuziDQ87WqZrjOlPJIOLU=",
    specialization: "Neurologist",
    appointmentDate: "2024-03-04",
    experience: "28 years",
    languages: ["Urdu"],
    hospitals: [
      "BLK-Max Super Specialty Hospital",
      "Rainbow Children's Hospital",
    ],
  },
  {
    id: 16,
    name: "Dr. Anita Roy",
    image:
      "https://media.istockphoto.com/id/1301595548/photo/female-doctor-stock-photo.jpg?s=612x612&w=0&k=20&c=s9kTlQCWJcYmCyMwYwJfTq7jiC1NfHaXzZyGhi4fRHM=",
    specialization: "Allergist, Urologist",
    appointmentDate: "2024-04-17",
    experience: "23 years",
    languages: ["Telugu", "Hindi", "Kannada"],
    hospitals: ["Medanta"],
  },
  {
    id: 17,
    name: "Dr. Anita Sharma",
    image:
      "https://static.vecteezy.com/system/resources/thumbnails/026/375/249/small_2x/ai-generative-portrait-of-confident-male-doctor-in-white-coat-and-stethoscope-standing-with-arms-crossed-and-looking-at-camera-photo.jpg",
    specialization: "Surgeon, General Practitioner, Nephrologist",
    appointmentDate: "2024-07-17",
    experience: "1 years",
    languages: ["Hindi"],
    hospitals: ["Fortis Healthcare"],
  },
  {
    id: 18,
    name: "Dr. Sunil Singh",
    image:
      "https://desunhospital.com/wp-content/uploads/2023/12/Dr.-Aditya-Varma-2-scaled.jpg",
    specialization: "Neurologist",
    appointmentDate: "2024-06-19",
    experience: "10 years",
    languages: ["Malayalam", "Telugu", "Punjabi"],
    hospitals: ["Fortis Healthcare"],
  },
  {
    id: 19,
    name: "Dr. Priya Reddy",
    image:
      "https://media.gettyimages.com/id/1400102237/photo/african-american-female-doctor-with-arms-crossed-over-white-background.jpg?s=612x612&w=gi&k=20&c=ciJ4r9W_z6cYdE_RM8eu-MQUj1tVRnQYJu9cTDC5c-Y=",
    specialization: "Gastroenterologist, Psychiatrist",
    appointmentDate: "2024-09-03",
    experience: "26 years",
    languages: ["Bengali", "Kannada", "Urdu", "Marathi"],
    hospitals: ["Fortis Healthcare", "AIIMS"],
  },
  {
    id: 20,
    name: "Dr. Kavita Roy",
    image:
      "https://www.shutterstock.com/image-photo/beautiful-african-american-nurse-arms-600nw-1936087690.jpg",
    specialization: "Urologist",
    appointmentDate: "2024-06-17",
    experience: "17 years",
    languages: ["Urdu", "Malayalam", "Hindi"],
    hospitals: ["Manipal Hospital", "Narayana Health"],
  },
  // {
  //   id: 21,
  //   name: "Dr. Raj Singh",
  //   image: "",
  //   specialization: "Urologist, Gynecologist, Neurologist",
  //   appointmentDate: "2024-09-23",
  //   experience: "6 years",
  //   languages: ["Bengali"],
  //   hospitals: ["Apollo Hospital"],
  // },
  // {
  //   id: 22,
  //   name: "Dr. Amit Reddy",
  //   image: "",
  //   specialization: "Immunologist, Endocrinologist, Pulmonologist",
  //   appointmentDate: "2024-08-24",
  //   experience: "30 years",
  //   languages: ["Tamil", "Gujarati", "Punjabi"],
  //   hospitals: ["Narayana Health"],
  // },
  // {
  //   id: 23,
  //   name: "Dr. Kavita Gupta",
  //   image: "",
  //   specialization: "Oncologist, Nephrologist, General Practitioner",
  //   appointmentDate: "2024-02-14",
  //   experience: "16 years",
  //   languages: ["Punjabi", "Kannada", "Tamil", "English"],
  //   hospitals: ["Narayana Health"],
  // },
  // {
  //   id: 24,
  //   name: "Dr. Priya Das",
  //   image: "",
  //   specialization: "Immunologist, Vascular Surgeon, Orthopedist",
  //   appointmentDate: "2024-11-26",
  //   experience: "12 years",
  //   languages: ["Bengali", "Urdu", "Tamil"],
  //   hospitals: ["Apollo Hospital"],
  // },
  // {
  //   id: 25,
  //   name: "Dr. Raj Kumar",
  //   image: "",
  //   specialization: "Cardiologist, Surgeon, General Practitioner",
  //   appointmentDate: "2024-10-05",
  //   experience: "11 years",
  //   languages: ["Kannada", "Telugu"],
  //   hospitals: ["Kokilaben Dhirubhai Ambani Hospital"],
  // },
  // {
  //   id: 26,
  //   name: "Dr. Raj Verma",
  //   image: "",
  //   specialization: "ENT Specialist, Endocrinologist, Allergist",
  //   appointmentDate: "2024-11-09",
  //   experience: "17 years",
  //   languages: ["Tamil", "Kannada"],
  //   hospitals: ["Kokilaben Dhirubhai Ambani Hospital", "Narayana Health"],
  // },
  // {
  //   id: 27,
  //   name: "Dr. Anita Reddy",
  //   image: "",
  //   specialization: "Anesthesiologist, Neurologist, ENT Specialist",
  //   appointmentDate: "2024-01-18",
  //   experience: "5 years",
  //   languages: ["Urdu"],
  //   hospitals: ["Medanta"],
  // },
  // {
  //   id: 28,
  //   name: "Dr. Anita Sharma",
  //   image: "",
  //   specialization: "Cardiologist, Urologist, Orthopedist",
  //   appointmentDate: "2024-10-25",
  //   experience: "12 years",
  //   languages: ["Gujarati", "Urdu"],
  //   hospitals: ["Kokilaben Dhirubhai Ambani Hospital", "Medanta"],
  // },
  // {
  //   id: 29,
  //   name: "Dr. Ravi Kumar",
  //   image: "",
  //   specialization: "General Practitioner, Nephrologist, Urologist",
  //   appointmentDate: "2024-11-08",
  //   experience: "19 years",
  //   languages: ["Kannada", "Gujarati", "Hindi"],
  //   hospitals: ["Medanta"],
  // },
  // {
  //   id: 30,
  //   name: "Dr. Pooja Kumar",
  //   image: "",
  //   specialization: "Dermatologist, Gynecologist",
  //   appointmentDate: "2024-03-10",
  //   experience: "26 years",
  //   languages: ["Urdu", "Marathi", "English"],
  //   hospitals: ["Rainbow Children's Hospital"],
  // },
  // {
  //   id: 31,
  //   name: "Dr. Anita Roy",
  //   image: "",
  //   specialization: "Hematologist",
  //   appointmentDate: "2024-01-17",
  //   experience: "3 years",
  //   languages: ["Malayalam", "Bengali", "Tamil"],
  //   hospitals: ["Max Healthcare"],
  // },
  // {
  //   id: 32,
  //   name: "Dr. Raj Verma",
  //   image: "",
  //   specialization: "Cardiologist",
  //   appointmentDate: "2024-09-19",
  //   experience: "7 years",
  //   languages: ["Bengali", "Urdu"],
  //   hospitals: ["Manipal Hospital", "BLK-Max Super Specialty Hospital"],
  // },
  // {
  //   id: 33,
  //   name: "Dr. Kavita Verma",
  //   image: "",
  //   specialization: "General Practitioner, Cardiologist",
  //   appointmentDate: "2024-10-03",
  //   experience: "26 years",
  //   languages: ["Bengali"],
  //   hospitals: ["Narayana Health", "BLK-Max Super Specialty Hospital"],
  // },
  // {
  //   id: 34,
  //   name: "Dr. Pooja Roy",
  //   image: "",
  //   specialization: "Cardiologist, Allergist",
  //   appointmentDate: "2024-11-15",
  //   experience: "26 years",
  //   languages: ["Gujarati", "Malayalam"],
  //   hospitals: ["Kokilaben Dhirubhai Ambani Hospital"],
  // },
  // {
  //   id: 35,
  //   name: "Dr. Kavita Reddy",
  //   image: "",
  //   specialization: "Gynecologist, Psychiatrist, Rheumatologist",
  //   appointmentDate: "2024-11-14",
  //   experience: "3 years",
  //   languages: ["Telugu", "Malayalam", "Bengali"],
  //   hospitals: ["Rainbow Children's Hospital"],
  // },
  // {
  //   id: 36,
  //   name: "Dr. Ravi Singh",
  //   image: "",
  //   specialization: "Hematologist",
  //   appointmentDate: "2024-01-17",
  //   experience: "29 years",
  //   languages: ["Gujarati", "Malayalam"],
  //   hospitals: ["Apollo Hospital"],
  // },
  // {
  //   id: 37,
  //   name: "Dr. Amit Das",
  //   image: "",
  //   specialization: "Psychiatrist, Radiologist",
  //   appointmentDate: "2024-02-19",
  //   experience: "27 years",
  //   languages: ["Urdu", "Telugu"],
  //   hospitals: ["Manipal Hospital"],
  // },
  // {
  //   id: 38,
  //   name: "Dr. Ravi Singh",
  //   image: "",
  //   specialization: "Gynecologist, Pediatrician, Ophthalmologist",
  //   appointmentDate: "2024-12-26",
  //   experience: "4 years",
  //   languages: ["Urdu", "Gujarati", "Telugu", "Punjabi"],
  //   hospitals: ["Fortis Healthcare", "Manipal Hospital"],
  // },
  // {
  //   id: 39,
  //   name: "Dr. Pooja Kumar",
  //   image: "",
  //   specialization: "Gynecologist, Oncologist, Endocrinologist",
  //   appointmentDate: "2024-07-01",
  //   experience: "22 years",
  //   languages: ["English", "Tamil", "Marathi"],
  //   hospitals: ["Manipal Hospital"],
  // },
  // {
  //   id: 40,
  //   name: "Dr. Anita Singh",
  //   image: "",
  //   specialization: "Hematologist, Pediatrician",
  //   appointmentDate: "2024-10-07",
  //   experience: "21 years",
  //   languages: ["Bengali"],
  //   hospitals: ["Max Healthcare"],
  // },
  // {
  //   id: 41,
  //   name: "Dr. Kavita Das",
  //   image: "",
  //   specialization: "Thoracic Surgeon, Allergist",
  //   appointmentDate: "2024-09-06",
  //   experience: "24 years",
  //   languages: ["Telugu", "Bengali"],
  //   hospitals: ["BLK-Max Super Specialty Hospital", "Narayana Health"],
  // },
  // {
  //   id: 42,
  //   name: "Dr. Pooja Reddy",
  //   image: "",
  //   specialization: "Radiologist, Gastroenterologist",
  //   appointmentDate: "2024-06-18",
  //   experience: "10 years",
  //   languages: ["Hindi", "English", "Bengali", "Gujarati"],
  //   hospitals: ["Kokilaben Dhirubhai Ambani Hospital"],
  // },
  // {
  //   id: 43,
  //   name: "Dr. Pooja Sharma",
  //   image: "",
  //   specialization: "Pediatrician, Neurologist, Gastroenterologist",
  //   appointmentDate: "2024-11-04",
  //   experience: "7 years",
  //   languages: ["Urdu", "Tamil", "Malayalam"],
  //   hospitals: ["Narayana Health"],
  // },
  // {
  //   id: 44,
  //   name: "Dr. Pooja Verma",
  //   image: "",
  //   specialization: "Allergist",
  //   appointmentDate: "2024-03-22",
  //   experience: "3 years",
  //   languages: ["Urdu", "Punjabi", "Marathi"],
  //   hospitals: ["AIIMS", "Apollo Hospital"],
  // },
  // {
  //   id: 45,
  //   name: "Dr. Raj Sharma",
  //   image: "",
  //   specialization: "Cardiologist",
  //   appointmentDate: "2024-03-21",
  //   experience: "17 years",
  //   languages: ["Urdu"],
  //   hospitals: ["AIIMS", "Apollo Hospital"],
  // },
  // {
  //   id: 46,
  //   name: "Dr. Kavita Das",
  //   image: "",
  //   specialization: "Vascular Surgeon, Psychiatrist",
  //   appointmentDate: "2024-06-01",
  //   experience: "21 years",
  //   languages: ["Marathi", "Tamil", "English", "Urdu"],
  //   hospitals: ["Manipal Hospital", "Kokilaben Dhirubhai Ambani Hospital"],
  // },
  // {
  //   id: 47,
  //   name: "Dr. Sunil Kumar",
  //   image: "",
  //   specialization: "Pediatrician, Dermatologist, Cardiologist",
  //   appointmentDate: "2024-12-18",
  //   experience: "19 years",
  //   languages: ["Punjabi", "Malayalam", "Gujarati", "Hindi"],
  //   hospitals: ["AIIMS", "Kokilaben Dhirubhai Ambani Hospital"],
  // },
  // {
  //   id: 48,
  //   name: "Dr. Pooja Sharma",
  //   image: "",
  //   specialization: "Psychiatrist",
  //   appointmentDate: "2024-09-26",
  //   experience: "13 years",
  //   languages: ["Gujarati", "Kannada"],
  //   hospitals: ["Fortis Healthcare"],
  // },
  // {
  //   id: 49,
  //   name: "Dr. Anita Kumar",
  //   image: "",
  //   specialization: "Psychiatrist",
  //   appointmentDate: "2024-10-08",
  //   experience: "20 years",
  //   languages: ["Malayalam", "Kannada", "Bengali", "Hindi"],
  //   hospitals: ["Max Healthcare", "AIIMS"],
  // },
  // {
  //   id: 50,
  //   name: "Dr. Ravi Das",
  //   image: "",
  //   specialization: "Rheumatologist",
  //   appointmentDate: "2024-12-07",
  //   experience: "4 years",
  //   languages: ["Tamil", "Urdu", "Gujarati", "Kannada"],
  //   hospitals: ["Narayana Health"],
  // },
  // {
  //   id: 51,
  //   name: "Dr. Anita Roy",
  //   image: "",
  //   specialization: "Rheumatologist, Nephrologist, Allergist",
  //   appointmentDate: "2024-06-17",
  //   experience: "19 years",
  //   languages: ["Kannada"],
  //   hospitals: ["Apollo Hospital"],
  // },
  // {
  //   id: 52,
  //   name: "Dr. Anita Singh",
  //   image: "",
  //   specialization: "Nephrologist, Pediatrician, Thoracic Surgeon",
  //   appointmentDate: "2024-12-13",
  //   experience: "25 years",
  //   languages: ["Urdu"],
  //   hospitals: ["Max Healthcare"],
  // },
  // {
  //   id: 53,
  //   name: "Dr. Priya Kumar",
  //   image: "",
  //   specialization: "Endocrinologist, General Practitioner, Allergist",
  //   appointmentDate: "2024-10-05",
  //   experience: "10 years",
  //   languages: ["Hindi", "Urdu", "Punjabi"],
  //   hospitals: ["Apollo Hospital", "Rainbow Children's Hospital"],
  // },
  // {
  //   id: 54,
  //   name: "Dr. Pooja Singh",
  //   image: "",
  //   specialization: "Gynecologist, Nephrologist, Orthopedist",
  //   appointmentDate: "2024-03-23",
  //   experience: "21 years",
  //   languages: ["Marathi", "Telugu", "Gujarati"],
  //   hospitals: ["Kokilaben Dhirubhai Ambani Hospital", "Apollo Hospital"],
  // },
  // {
  //   id: 55,
  //   name: "Dr. Sunil Singh",
  //   image: "",
  //   specialization: "Hematologist",
  //   appointmentDate: "2024-03-15",
  //   experience: "13 years",
  //   languages: ["Tamil", "Bengali", "English"],
  //   hospitals: ["Fortis Healthcare", "Manipal Hospital"],
  // },
  // {
  //   id: 56,
  //   name: "Dr. Amit Verma",
  //   image: "",
  //   specialization: "Thoracic Surgeon",
  //   appointmentDate: "2024-10-08",
  //   experience: "19 years",
  //   languages: ["Marathi", "Kannada"],
  //   hospitals: ["Max Healthcare", "Narayana Health"],
  // },
  // {
  //   id: 57,
  //   name: "Dr. Priya Sharma",
  //   image: "",
  //   specialization: "Vascular Surgeon",
  //   appointmentDate: "2024-08-15",
  //   experience: "19 years",
  //   languages: ["Gujarati", "Punjabi", "Hindi"],
  //   hospitals: ["Narayana Health", "AIIMS"],
  // },
  // {
  //   id: 58,
  //   name: "Dr. Sunil Reddy",
  //   image: "",
  //   specialization: "Cardiologist, Orthopedist",
  //   appointmentDate: "2024-04-28",
  //   experience: "17 years",
  //   languages: ["Marathi", "Tamil", "Kannada"],
  //   hospitals: ["Manipal Hospital"],
  // },
  // {
  //   id: 59,
  //   name: "Dr. Pooja Das",
  //   image: "",
  //   specialization: "Radiologist, Orthopedist",
  //   appointmentDate: "2024-09-19",
  //   experience: "12 years",
  //   languages: ["Urdu", "Gujarati"],
  //   hospitals: ["Manipal Hospital"],
  // },
  // {
  //   id: 60,
  //   name: "Dr. Amit Verma",
  //   image: "",
  //   specialization: "Endocrinologist, Radiologist",
  //   appointmentDate: "2024-12-23",
  //   experience: "19 years",
  //   languages: ["Telugu", "Marathi", "Gujarati"],
  //   hospitals: ["Kokilaben Dhirubhai Ambani Hospital"],
  // },
  // {
  //   id: 61,
  //   name: "Dr. Kavita Singh",
  //   image: "",
  //   specialization: "Nephrologist, Dermatologist",
  //   appointmentDate: "2024-08-22",
  //   experience: "15 years",
  //   languages: ["Malayalam", "Kannada", "Punjabi"],
  //   hospitals: ["Manipal Hospital", "Kokilaben Dhirubhai Ambani Hospital"],
  // },
  // {
  //   id: 62,
  //   name: "Dr. Ravi Kumar",
  //   image: "",
  //   specialization: "General Practitioner",
  //   appointmentDate: "2024-11-05",
  //   experience: "21 years",
  //   languages: ["Gujarati", "Tamil", "Hindi", "Bengali"],
  //   hospitals: ["Max Healthcare"],
  // },
  // {
  //   id: 63,
  //   name: "Dr. Raj Roy",
  //   image: "",
  //   specialization: "Orthopedist",
  //   appointmentDate: "2024-11-24",
  //   experience: "25 years",
  //   languages: ["Malayalam"],
  //   hospitals: ["AIIMS"],
  // },
  // {
  //   id: 64,
  //   name: "Dr. Anita Sharma",
  //   image: "",
  //   specialization: "Neurologist, Dermatologist, Immunologist",
  //   appointmentDate: "2024-09-28",
  //   experience: "15 years",
  //   languages: ["Punjabi", "Hindi"],
  //   hospitals: ["Apollo Hospital"],
  // },
  // {
  //   id: 65,
  //   name: "Dr. Anita Verma",
  //   image: "",
  //   specialization: "Radiologist, Neurologist",
  //   appointmentDate: "2024-10-04",
  //   experience: "26 years",
  //   languages: ["Urdu", "Gujarati", "Kannada"],
  //   hospitals: ["Rainbow Children's Hospital", "Narayana Health"],
  // },
  // {
  //   id: 66,
  //   name: "Dr. Raj Reddy",
  //   image: "",
  //   specialization: "Thoracic Surgeon, Allergist, Endocrinologist",
  //   appointmentDate: "2024-07-01",
  //   experience: "2 years",
  //   languages: ["Gujarati", "Bengali", "Tamil"],
  //   hospitals: ["Medanta"],
  // },
  // {
  //   id: 67,
  //   name: "Dr. Ravi Kumar",
  //   image: "",
  //   specialization: "Anesthesiologist, Immunologist",
  //   appointmentDate: "2024-05-06",
  //   experience: "14 years",
  //   languages: ["Tamil", "Gujarati"],
  //   hospitals: ["AIIMS"],
  // },
  // {
  //   id: 68,
  //   name: "Dr. Ravi Gupta",
  //   image: "",
  //   specialization: "Oncologist, Urologist, Radiologist",
  //   appointmentDate: "2024-08-03",
  //   experience: "20 years",
  //   languages: ["Malayalam", "Hindi", "Marathi"],
  //   hospitals: ["Max Healthcare"],
  // },
  // {
  //   id: 69,
  //   name: "Dr. Kavita Reddy",
  //   image: "",
  //   specialization: "General Practitioner, Gastroenterologist",
  //   appointmentDate: "2024-06-15",
  //   experience: "12 years",
  //   languages: ["Marathi", "English"],
  //   hospitals: ["AIIMS"],
  // },
  // {
  //   id: 70,
  //   name: "Dr. Pooja Sharma",
  //   image: "",
  //   specialization: "Dermatologist, Ophthalmologist, Immunologist",
  //   appointmentDate: "2024-05-17",
  //   experience: "30 years",
  //   languages: ["Kannada"],
  //   hospitals: ["Rainbow Children's Hospital"],
  // },
  // {
  //   id: 71,
  //   name: "Dr. Pooja Sharma",
  //   image: "",
  //   specialization: "Dermatologist, Urologist",
  //   appointmentDate: "2024-05-09",
  //   experience: "29 years",
  //   languages: ["Tamil", "Malayalam"],
  //   hospitals: ["Manipal Hospital"],
  // },
  // {
  //   id: 72,
  //   name: "Dr. Amit Das",
  //   image: "",
  //   specialization: "Dermatologist, Orthopedist, Vascular Surgeon",
  //   appointmentDate: "2024-10-25",
  //   experience: "19 years",
  //   languages: ["Gujarati", "Hindi"],
  //   hospitals: ["Apollo Hospital", "Medanta"],
  // },
  // {
  //   id: 73,
  //   name: "Dr. Amit Verma",
  //   image: "",
  //   specialization: "Pediatrician, Psychiatrist, Neurologist",
  //   appointmentDate: "2024-08-02",
  //   experience: "22 years",
  //   languages: ["Urdu", "Gujarati", "English"],
  //   hospitals: ["Medanta", "Max Healthcare"],
  // },
  // {
  //   id: 74,
  //   name: "Dr. Pooja Singh",
  //   image: "",
  //   specialization: "Oncologist",
  //   appointmentDate: "2024-02-01",
  //   experience: "21 years",
  //   languages: ["Marathi", "Kannada", "Gujarati", "Punjabi"],
  //   hospitals: ["AIIMS", "Manipal Hospital"],
  // },
  // {
  //   id: 75,
  //   name: "Dr. Pooja Verma",
  //   image: "",
  //   specialization: "Radiologist",
  //   appointmentDate: "2024-04-07",
  //   experience: "5 years",
  //   languages: ["Bengali", "Marathi", "Gujarati"],
  //   hospitals: ["Narayana Health", "Fortis Healthcare"],
  // },
  // {
  //   id: 76,
  //   name: "Dr. Raj Das",
  //   image: "",
  //   specialization: "Rheumatologist, ENT Specialist, Dermatologist",
  //   appointmentDate: "2024-10-02",
  //   experience: "21 years",
  //   languages: ["Malayalam", "Telugu"],
  //   hospitals: ["Narayana Health", "Apollo Hospital"],
  // },
  // {
  //   id: 77,
  //   name: "Dr. Anita Das",
  //   image: "",
  //   specialization: "Gynecologist, Dermatologist, Radiologist",
  //   appointmentDate: "2024-07-26",
  //   experience: "9 years",
  //   languages: ["Kannada", "Hindi", "Malayalam"],
  //   hospitals: ["Medanta", "Kokilaben Dhirubhai Ambani Hospital"],
  // },
  // {
  //   id: 78,
  //   name: "Dr. Ravi Gupta",
  //   image: "",
  //   specialization: "General Practitioner, ENT Specialist, Allergist",
  //   appointmentDate: "2024-07-20",
  //   experience: "26 years",
  //   languages: ["Kannada", "Bengali", "Malayalam"],
  //   hospitals: ["AIIMS", "Manipal Hospital"],
  // },
  // {
  //   id: 79,
  //   name: "Dr. Amit Sharma",
  //   image: "",
  //   specialization: "Psychiatrist, General Practitioner",
  //   appointmentDate: "2024-06-13",
  //   experience: "23 years",
  //   languages: ["Malayalam", "Punjabi", "Hindi", "Telugu"],
  //   hospitals: ["Apollo Hospital"],
  // },
  // {
  //   id: 80,
  //   name: "Dr. Anita Reddy",
  //   image: "",
  //   specialization: "Cardiologist",
  //   appointmentDate: "2024-08-01",
  //   experience: "22 years",
  //   languages: ["Tamil"],
  //   hospitals: ["Fortis Healthcare"],
  // },
  // {
  //   id: 81,
  //   name: "Dr. Priya Sharma",
  //   image: "",
  //   specialization: "Vascular Surgeon, General Practitioner",
  //   appointmentDate: "2024-01-15",
  //   experience: "28 years",
  //   languages: ["Kannada", "Urdu", "Telugu"],
  //   hospitals: ["Medanta"],
  // },
  // {
  //   id: 82,
  //   name: "Dr. Priya Reddy",
  //   image: "",
  //   specialization: "Dermatologist, Endocrinologist",
  //   appointmentDate: "2024-05-04",
  //   experience: "9 years",
  //   languages: ["Punjabi", "Gujarati", "English"],
  //   hospitals: ["Fortis Healthcare"],
  // },
  // {
  //   id: 83,
  //   name: "Dr. Ravi Kumar",
  //   image: "",
  //   specialization: "Plastic Surgeon, ENT Specialist",
  //   appointmentDate: "2024-02-15",
  //   experience: "9 years",
  //   languages: ["Hindi", "Punjabi", "Tamil"],
  //   hospitals: ["Max Healthcare"],
  // },
  // {
  //   id: 84,
  //   name: "Dr. Anita Gupta",
  //   image: "",
  //   specialization: "Vascular Surgeon, Cardiologist, Orthopedist",
  //   appointmentDate: "2024-12-18",
  //   experience: "30 years",
  //   languages: ["Malayalam", "Hindi", "Urdu"],
  //   hospitals: ["Fortis Healthcare"],
  // },
  // {
  //   id: 85,
  //   name: "Dr. Amit Gupta",
  //   image: "",
  //   specialization: "Hematologist",
  //   appointmentDate: "2024-01-18",
  //   experience: "18 years",
  //   languages: ["English", "Bengali", "Tamil", "Malayalam"],
  //   hospitals: ["Manipal Hospital"],
  // },
  // {
  //   id: 86,
  //   name: "Dr. Kavita Das",
  //   image: "",
  //   specialization: "Plastic Surgeon, Surgeon",
  //   appointmentDate: "2024-10-25",
  //   experience: "19 years",
  //   languages: ["Hindi", "Kannada", "Punjabi"],
  //   hospitals: ["AIIMS", "Medanta"],
  // },
  // {
  //   id: 87,
  //   name: "Dr. Priya Reddy",
  //   image: "",
  //   specialization: "Vascular Surgeon, Anesthesiologist",
  //   appointmentDate: "2024-11-16",
  //   experience: "26 years",
  //   languages: ["Marathi", "Malayalam"],
  //   hospitals: ["BLK-Max Super Specialty Hospital", "Manipal Hospital"],
  // },
  // {
  //   id: 88,
  //   name: "Dr. Raj Gupta",
  //   image: "",
  //   specialization: "Dermatologist",
  //   appointmentDate: "2024-12-06",
  //   experience: "4 years",
  //   languages: ["Gujarati", "Malayalam", "Tamil"],
  //   hospitals: ["Fortis Healthcare"],
  // },
  // {
  //   id: 89,
  //   name: "Dr. Anita Sharma",
  //   image: "",
  //   specialization: "Surgeon",
  //   appointmentDate: "2024-10-23",
  //   experience: "4 years",
  //   languages: ["Punjabi", "Malayalam"],
  //   hospitals: ["BLK-Max Super Specialty Hospital", "Fortis Healthcare"],
  // },
  // {
  //   id: 90,
  //   name: "Dr. Anita Das",
  //   image: "",
  //   specialization: "Gastroenterologist",
  //   appointmentDate: "2024-02-14",
  //   experience: "5 years",
  //   languages: ["Gujarati"],
  //   hospitals: ["Max Healthcare"],
  // },
  // {
  //   id: 91,
  //   name: "Dr. Ravi Reddy",
  //   image: "",
  //   specialization: "Psychiatrist, Gastroenterologist",
  //   appointmentDate: "2024-02-08",
  //   experience: "14 years",
  //   languages: ["Urdu", "Telugu", "Bengali", "Kannada"],
  //   hospitals: ["Fortis Healthcare"],
  // },
  // {
  //   id: 92,
  //   name: "Dr. Sunil Gupta",
  //   image: "",
  //   specialization: "Orthopedist",
  //   appointmentDate: "2024-06-08",
  //   experience: "29 years",
  //   languages: ["Telugu", "Gujarati"],
  //   hospitals: ["Apollo Hospital", "AIIMS"],
  // },
  // {
  //   id: 93,
  //   name: "Dr. Kavita Sharma",
  //   image: "",
  //   specialization: "Dermatologist",
  //   appointmentDate: "2024-03-13",
  //   experience: "5 years",
  //   languages: ["Telugu", "Urdu"],
  //   hospitals: ["Manipal Hospital"],
  // },
  // {
  //   id: 94,
  //   name: "Dr. Amit Kumar",
  //   image: "",
  //   specialization: "Gastroenterologist, Plastic Surgeon, ENT Specialist",
  //   appointmentDate: "2024-12-16",
  //   experience: "3 years",
  //   languages: ["Punjabi"],
  //   hospitals: ["Apollo Hospital"],
  // },
  // {
  //   id: 95,
  //   name: "Dr. Kavita Sharma",
  //   image: "",
  //   specialization: "Oncologist",
  //   appointmentDate: "2024-11-15",
  //   experience: "22 years",
  //   languages: ["Urdu", "Tamil", "Marathi"],
  //   hospitals: ["Rainbow Children's Hospital"],
  // },
  // {
  //   id: 96,
  //   name: "Dr. Raj Sharma",
  //   image: "",
  //   specialization: "Gynecologist",
  //   appointmentDate: "2024-12-05",
  //   experience: "28 years",
  //   languages: ["Malayalam", "Bengali", "Tamil"],
  //   hospitals: ["Apollo Hospital"],
  // },
  // {
  //   id: 97,
  //   name: "Dr. Sunil Gupta",
  //   image: "",
  //   specialization: "Gynecologist, Dermatologist",
  //   appointmentDate: "2024-11-07",
  //   experience: "1 years",
  //   languages: ["Telugu", "Tamil", "Urdu"],
  //   hospitals: ["Kokilaben Dhirubhai Ambani Hospital", "Max Healthcare"],
  // },
  // {
  //   id: 98,
  //   name: "Dr. Ravi Sharma",
  //   image: "",
  //   specialization: "Psychiatrist, Endocrinologist",
  //   appointmentDate: "2024-02-04",
  //   experience: "24 years",
  //   languages: ["English", "Telugu", "Hindi"],
  //   hospitals: ["Medanta"],
  // },
  // {
  //   id: 99,
  //   name: "Dr. Priya Verma",
  //   image: "",
  //   specialization: "Rheumatologist",
  //   appointmentDate: "2024-09-18",
  //   experience: "7 years",
  //   languages: ["Telugu", "Bengali"],
  //   hospitals: ["Kokilaben Dhirubhai Ambani Hospital"],
  // },
  // {
  //   id: 100,
  //   name: "Dr. Priya Gupta",
  //   image: "",
  //   specialization: "Hematologist",
  //   appointmentDate: "2024-01-10",
  //   experience: "13 years",
  //   languages: ["Bengali"],
  //   hospitals: ["Medanta"],
  // },
];

export const hospitals = [
  {
    name: "All India Institute of Medical Sciences (AIIMS), New Delhi",
    image: "https://nsventures.in/wp-content/uploads/2022/08/AIIMS.jpg",
    description:
      "AIIMS New Delhi is one of India's most prestigious hospitals, offering comprehensive healthcare services, advanced medical research, and education.",
  },
  {
    name: "Apollo Hospitals, Chennai",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQMNwfgIE6y-hBkIwwvraRu8ZQJ9q-ik_Ku6w&s",
    description:
      "Apollo Hospitals is a chain of hospitals offering advanced medical care across various specialties, known for its world-class infrastructure and expertise.",
  },
  {
    name: "Fortis Healthcare, Gurgaon",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRbYre_RjYaG9C-OGfcpLCSsBN4YxaG2pMy6w&s",
    description:
      "Fortis Healthcare is a leading hospital network in India, offering high-quality healthcare services with a focus on patient-centric care.",
  },
  {
    name: "Medanta – The Medicity, Gurgaon",
    image:
      "https://www.medanta.org/storage/about/November2023//0HHQ3u5UygpI31qpRpcaaytP7VaLJh-metaR3VydWdyYW0uanBn-.jpg",
    description:
      "Medanta is a multi-specialty medical institute providing world-class healthcare services with state-of-the-art facilities and advanced technologies.",
  },
  {
    name: "Max Healthcare, New Delhi",
    image:
      "https://content.jdmagicbox.com/v2/comp/delhi/j1/011pxx11.xx11.230424200451.t5j1/catalogue/max-super-speciality-hospital-rajendra-place-delhi-multispeciality-hospitals-4w33b5syfj.jpg",
    description:
      "Max Healthcare is a prominent healthcare provider offering a wide range of medical services, with a focus on advanced treatment and patient care.",
  },
  {
    name: "Kokilaben Dhirubhai Ambani Hospital, Mumbai",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTUSN3t95KE_SM7sOSWFvqU6crraB2mNC-T6A&s",
    description:
      "Kokilaben Hospital is a multi-specialty medical center offering cutting-edge healthcare services and a commitment to excellence in patient care.",
  },
  {
    name: "Manipal Hospitals, Bangalore",
    image:
      "https://s3.ap-south-1.amazonaws.com/media.production.in/hospitals/images/1692274706589.jpg",
    description:
      "Manipal Hospitals is one of India's leading healthcare providers with a strong presence in multiple specialties and a reputation for quality care.",
  },
  {
    name: "Lilavati Hospital, Mumbai",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSs77dHOmsy0M4qJUemA4ajOv9iJB_jtDqvvg&s",
    description:
      "Lilavati Hospital is a renowned healthcare institution offering high-quality medical services, including specialized care in various fields.",
  },
  {
    name: "Narayana Health, Bangalore",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRHGI1dnx9FHsJTpoOBhNLdGqXRYD7DSQHTJQ&s",
    description:
      "Narayana Health is known for providing world-class healthcare services at affordable prices, specializing in heart care, oncology, and more.",
  },
  {
    name: "Tata Memorial Hospital, Mumbai",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSjVCSDdYdgJYktI6KX9dmSCwnFjJydi0Qy6g&s",
    description:
      "Tata Memorial Hospital is one of India's leading cancer care institutions, offering advanced treatments and research in oncology.",
  },
  {
    name: "Apollo Gleneagles Hospital, Kolkata",
    image:
      "https://cdn.apollohospitals.com/dev-apollohospitals/2020/11/apollo-hospital-kolkata.jpg",
    description:
      "Apollo Gleneagles offers multi-specialty healthcare services with a strong reputation for quality treatment and patient satisfaction.",
  },
  {
    name: "Sankara Nethralaya, Chennai",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSRcH0FL8p-c4P820OEUx_iy84hG-Q4WTjBQQ&s",
    description:
      "Sankara Nethralaya is a world-renowned eye hospital known for its advanced ophthalmology services and charitable approach to care.",
  },
  {
    name: "SRM Institute of Medical Sciences, Chennai",
    image:
      "https://www.srmhospital.co.in/wp-content/themes/eightmedi-lite/images/srm/Home-Page-Banner4.png",
    description:
      "SRM Institute of Medical Sciences provides state-of-the-art medical care and is renowned for its research and teaching in healthcare.",
  },
  {
    name: "Wockhardt Hospitals, Mumbai",
    image:
      "https://www.myhospitalnow.com/hospitals/storage/hospital_profile/wockh-128616115_1701515227.jpg",
    description:
      "Wockhardt Hospitals offers advanced healthcare facilities across multiple specialties, including cardiac care, neurology, and more.",
  },
  {
    name: "The Christian Medical College (CMC), Vellore",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ7sxkmyAFfjJzp-1wFvH0gC-wDjWOigcrNnA&s",
    description:
      "CMC Vellore is one of India's oldest and most respected healthcare institutions, offering comprehensive services and medical education.",
  },
  {
    name: "Breach Candy Hospital, Mumbai",
    image:
      "https://content3.jdmagicbox.com/v2/comp/mumbai/u1/022pxx22.xx22.000783548548.j9u1/catalogue/breach-candy-hospital-breach-candy-mumbai-pathology-labs-32lcm.jpg",
    description:
      "Breach Candy Hospital is a well-known private hospital offering specialized care in cardiology, neurology, and other fields.",
  },
  {
    name: "Aster CMI Hospital, Bangalore",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRHERUSb6DVtP1k-kRZXR3VzW-jngCE9B2qlQ&s",
    description:
      "Aster CMI is a multi-specialty hospital in Bangalore, providing cutting-edge medical care with a focus on advanced technology and compassionate care.",
  },
  {
    name: "Care Hospitals, Hyderabad",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQnfMz0h591ArlghLBxMRDg9HAQUAblN4IO-g&s",
    description:
      "Care Hospitals offer a wide range of medical services, known for their exceptional care in areas such as cardiology, oncology, and orthopedics.",
  },
  {
    name: "Jaypee Hospital, Noida",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTCRjR_TopZK4K0_xO6OlHjFNX8YQIIYUxMhA&s",
    description:
      "Jaypee Hospital is a multi-specialty facility offering high-quality healthcare services, with specialized departments and advanced diagnostic tools.",
  },
  {
    name: "Ramakrishna Mission Seva Pratishthan, Kolkata",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_M6n_yBjVJJvJ9UL35nBbRD6yvdy9FOsiPg&s",
    description:
      "Ramakrishna Mission Seva Pratishthan is a charitable hospital focused on providing medical care to all, particularly to the underprivileged.",
  },
  {
    name: "Hiranandani Hospital, Mumbai",
    image:
      "https://www.rateyourtreatment.com/Hospital_Images/Dr_LH_Hiranandani_Hospital_Mumbai.JPG",
    description:
      "Hiranandani Hospital offers world-class healthcare with a focus on personalized care, with specialties ranging from cardiology to orthopedics.",
  },
  {
    name: "Fortis La Femme Hospital, New Delhi",
    image:
      "https://content3.jdmagicbox.com/v2/comp/delhi/h4/011pxx11.xx11.090608111523.w8h4/catalogue/fortis-la-femme-delhi-1utbdhy4rk.jpg",
    description:
      "Fortis La Femme is a leading hospital dedicated to women's healthcare, offering specialized services in gynecology, obstetrics, and more.",
  },
  {
    name: "Shree Harsha Hospital, Bangalore",
    image:
      "https://content.jdmagicbox.com/comp/mahabubnagar/dc/9999px240.x240.1238168630x5a2s1.dc/catalogue/sri-harsha-neuropsychiatric-clinic-new-town-mahabubnagar-hospitals-k2kdzcrkl7.jpg",
    description:
      "Shree Harsha Hospital is known for its patient care, providing treatment across a wide range of specialties with a focus on affordability.",
  },
  {
    name: "Alchemist Hospital, Panchkula",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTYoEDYmaV_f6J6gqzYlUmyXycbc2zOXTU4eQ&s",
    description:
      "Alchemist Hospital offers state-of-the-art medical care with a focus on the latest treatment technologies and compassionate patient services.",
  },
  {
    name: "Cloudnine Hospital, Bangalore",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQWoLc75xQwFNEkQgvRY7HgqvlBnTK35myqLg&s",
    description:
      "Cloudnine Hospital is a well-known maternity and pediatric healthcare provider, offering services across various specialties for women and children.",
  },
];
